### ISSUE TITLE
Lege HTML

### ISSUE THREAD

**Issue by krijnhoetmer** [romerdev/the-client-case#5]
Je navigatie is leeg. Ik begrijp dat je die er met JS in gooit, maar kun je iets verzinnen waardoor er initieel in je HTML al iets staat waar je iets mee kunt? Je maakt JS nu volledig vereist voor je applicatie. Logisch voor een kaart, maar voor een lijst met links/navigatie zou ik het iets simpeler maken. Ander voordeel: de browser heeft minder werk te doen (en het wordt dus sneller).

https://github.com/romerdev/the-client-case/blob/7fdd11db35e921422095fc30f6d0cf1925efb656/index.html#L37-L39

**Comment by romerdev** [comment]
Thanks! Dit heb ik opgelost door de <ul> handmatig te vullen. Zodra JavaScript het doet, wordt de <ul> leeggehaald en er opnieuw ingezet met de juiste data-attributen die de click event mogelijk maken.
